#!/bin/bash

mkdir -p build
cd build

# Install dependencies with Conan
conan install .. --build=missing

# Source the environment setup script generated by Conan
. Release/generators/conanbuild.sh

# Go back to project root to use presets
cd ..

# Source the python virtual environment
source venv/bin/activate

# Configure CMake using the preset generated by Conan
cmake --preset conan-release

# Build
cmake --build build/Release --config Release